services: docker

matrix:
  include:
    - language: php
      name: "7.4"

before_script: docker build --build-arg PHP_VERSION=${TRAVIS_JOB_NAME} -t opis-closure .
script: docker run opis-closure /source/vendor/bin/phpunit