language: php

matrix:
  include:
    - php: 7.4
      dist: bionic
      before_install:
        - sudo apt-get -y -q=2 --no-install-recommends --no-install-suggests install libffi-dev php-ffi

install: travis_retry composer install

script: vendor/bin/phpunit
