name: "Tests"
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php: [7.4]
        zts: [ts, nts]
        exclude:
          - os: ubuntu-latest
            zts: ts
          - os: macos-latest
            zts: ts

    runs-on: ${{ matrix.os }}

    name: PHP ${{ matrix.php }} on ${{ matrix.os }} with ${{ matrix.zts }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ffi
          coverage: none
        env:
          phpts: ${{ matrix.zts }}

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --verbose